#!/usr/bin/python
import re
def main():
    stopwords = [ 'ab', 'ac', 'ad', 'adhic', 'aliqui', 'aliquis', 'an', 'ante',
        'apud', 'at', 'atque', 'aut', 'autem', 'cum', 'cur', 'de', 'deinde',
        'dum', 'ego', 'enim', 'ergo', 'es', 'est', 'et', 'etiam', 'etsi', 'ex',
        'fio', 'haud', 'hic', 'iam', 'idem', 'igitur', 'ille', 'in', 'infra',
        'inter', 'interim', 'ipse', 'is', 'ita', 'magis', 'modo', 'mox', 'nam',
        'ne', 'nec', 'necque', 'neque', 'nisi', 'non', 'nos', 'o', 'ob', 'per',
        'possum', 'post', 'pro', 'quae', 'quam', 'quare', 'qui', 'quia',
        'quicumque', 'quidem', 'quilibet', 'quis', 'quisnam', 'quisquam',
        'quisque', 'quisquis', 'quo', 'quoniam', 'sed', 'si', 'sic', 'sive',
        'sub', 'sui', 'sum', 'super', 'suus', 'tam', 'tamen', 'trans', 'tu',
        'tum', 'ubi', 'uel', 'uero']
    patterns =[]
    for stopword in stopwords:
        # pattern = 'r\'\\b' + stopword + '\\b\''
        patterns.append('r\'\\b' + stopword + '\\b\'')
    f = open('./gratian.txt', 'r')
    for line in f:
        # line = re.sub(r'\-.*?\+', '', line)
        # line = re.sub(r'\<.*?\>', '', line)
        line = re.sub(r'\bab\b', '', line)
        line = re.sub(r'\bac\b', '', line)
        line = re.sub(r'\bad\b', '', line)
        line = re.sub(r'\badhic\b', '', line)
        line = re.sub(r'\baliqui\b', '', line)
        line = re.sub(r'\baliquis\b', '', line)
        line = re.sub(r'\ban\b', '', line)
        line = re.sub(r'\bante\b', '', line)
        line = re.sub(r'\bapud\b', '', line)
        line = re.sub(r'\bat\b', '', line)
        line = re.sub(r'\batque\b', '', line)
        line = re.sub(r'\baut\b', '', line)
        line = re.sub(r'\bautem\b', '', line)
        line = re.sub(r'\bcum\b', '', line)
        line = re.sub(r'\bcur\b', '', line)
        line = re.sub(r'\bde\b', '', line)
        line = re.sub(r'\bdeinde\b', '', line)
        line = re.sub(r'\bdum\b', '', line)
        line = re.sub(r'\bego\b', '', line)
        line = re.sub(r'\benim\b', '', line)
        line = re.sub(r'\bergo\b', '', line)
        line = re.sub(r'\bes\b', '', line)
        line = re.sub(r'\best\b', '', line)
        line = re.sub(r'\bet\b', '', line)
        line = re.sub(r'\betiam\b', '', line)
        line = re.sub(r'\betsi\b', '', line)
        line = re.sub(r'\bex\b', '', line)
        line = re.sub(r'\bfio\b', '', line)
        line = re.sub(r'\bhaud\b', '', line)
        line = re.sub(r'\bhic\b', '', line)
        line = re.sub(r'\biam\b', '', line)
        line = re.sub(r'\bidem\b', '', line)
        line = re.sub(r'\bigitur\b', '', line)
        line = re.sub(r'\bille\b', '', line)
        line = re.sub(r'\bin\b', '', line)
        line = re.sub(r'\binfra\b', '', line)
        line = re.sub(r'\binter\b', '', line)
        line = re.sub(r'\binterim\b', '', line)
        line = re.sub(r'\bipse\b', '', line)
        line = re.sub(r'\bis\b', '', line)
        line = re.sub(r'\bita\b', '', line)
        line = re.sub(r'\bmagis\b', '', line)
        line = re.sub(r'\bmodo\b', '', line)
        line = re.sub(r'\bmox\b', '', line)
        line = re.sub(r'\bnam\b', '', line)
        line = re.sub(r'\bne\b', '', line)
        line = re.sub(r'\bnec\b', '', line)
        line = re.sub(r'\bnecque\b', '', line)
        line = re.sub(r'\bneque\b', '', line)
        line = re.sub(r'\bnisi\b', '', line)
        line = re.sub(r'\bnon\b', '', line)
        line = re.sub(r'\bnos\b', '', line)
        line = re.sub(r'\bo\b', '', line)
        line = re.sub(r'\bob\b', '', line)
        line = re.sub(r'\bper\b', '', line)
        line = re.sub(r'\bpossum\b', '', line)
        line = re.sub(r'\bpost\b', '', line)
        line = re.sub(r'\bpro\b', '', line)
        line = re.sub(r'\bquae\b', '', line)
        line = re.sub(r'\bquam\b', '', line)
        line = re.sub(r'\bquare\b', '', line)
        line = re.sub(r'\bqui\b', '', line)
        line = re.sub(r'\bquia\b', '', line)
        line = re.sub(r'\bquicumque\b', '', line)
        line = re.sub(r'\bquidem\b', '', line)
        line = re.sub(r'\bquilibet\b', '', line)
        line = re.sub(r'\bquis\b', '', line)
        line = re.sub(r'\bquisnam\b', '', line)
        line = re.sub(r'\bquisquam\b', '', line)
        line = re.sub(r'\bquisque\b', '', line)
        line = re.sub(r'\bquisquis\b', '', line)
        line = re.sub(r'\bquo\b', '', line)
        line = re.sub(r'\bquoniam\b', '', line)
        line = re.sub(r'\bsed\b', '', line)
        line = re.sub(r'\bsi\b', '', line)
        line = re.sub(r'\bsic\b', '', line)
        line = re.sub(r'\bsive\b', '', line)
        line = re.sub(r'\bsub\b', '', line)
        line = re.sub(r'\bsui\b', '', line)
        line = re.sub(r'\bsum\b', '', line)
        line = re.sub(r'\bsuper\b', '', line)
        line = re.sub(r'\bsuus\b', '', line)
        line = re.sub(r'\btam\b', '', line)
        line = re.sub(r'\btamen\b', '', line)
        line = re.sub(r'\btrans\b', '', line)
        line = re.sub(r'\btu\b', '', line)
        line = re.sub(r'\btum\b', '', line)
        line = re.sub(r'\bubi\b', '', line)
        line = re.sub(r'\buel\b', '', line)
        line = re.sub(r'\buero\b', '', line)
        print line.rstrip() # like Perl chop

if __name__ == '__main__':
    main()
